### ISSUE TITLE
HTTP response status is 406 for Batching

### ISSUE THREAD

**Issue by coladarci** [Logflare/logflare_logger_backend#38]
I just followed the guides w/out anything custom happening and am seeing this:
```
warning: Logflare API warning: HTTP response status is 406
  (logflare_logger_backend 0.7.6) lib/logflare_logger/batch_cache.ex:49: LogflareLogger.BatchCache.flush/1
  (logflare_logger_backend 0.7.6) lib/logflare_logger/http_backend.ex:113: LogflareLogger.HttpBackend.flush!/1
  (stdlib 3.13) gen_event.erl:620: :gen_event.server_update/4
  (stdlib 3.13) gen_event.erl:602: :gen_event.server_notify/4
  (stdlib 3.13) gen_event.erl:604: :gen_event.server_notify/4
  (stdlib 3.13) gen_event.erl:390: :gen_event.handle_msg/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I still see logs showing up, just curious about this 406. 

Thanks!

**Comment by chasers** [comment]
You may be logging a field name it doesn't like or the data might not be typechecking against your schema. 

You can go to `https://logflare.app/sources/[ID]/rejected` and if a log event fails to validate against your schema, or if it fails to validate because we can't turn the field name into a BigQuery compatible column name, it will show up there.  For reference: `A column name must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_), and it must start with a letter or underscore.`

If you email your source url or the source uuid to support@logflare.app I can help with more specifics.

Thanks for trying Logflare!

**Comment by chasers** [comment]
Seems it was a `-` in a field name when logging request / response headers.

Closing here in favor of a #39
